mutation createRekapKegiatan(
  $program: String,
  $kegiatan: String,
  $pekerjaan: String,
  $desa: String,
  $kecamatan: String,
  $nomor_kontrak: String,
  $nilai_kontrak: String,
  $nama_rekanan: String,
  $tgl_mulai: Date,
  $tgl_selesai: Date

) {
  createRekapKegiatan(input: {data: {
    program: $program, 
    kegiatan: $kegiatan,
    pekerjaan: $pekerjaan,
    desa: $desa,
    kecamatan: $kecamatan,
    nomor_kontrak: $nomor_kontrak,
    nilai_kontrak: $nilai_kontrak,
    nama_rekanan: $nama_rekanan
    tgl_mulai: $tgl_mulai,
    tgl_selesai: $tgl_selesai 
    
}}) {
    rekapKegiatan {
      program
      kegiatan
      pekerjaan
      desa
      kecamatan
      nomor_kontrak
      nilai_kontrak
      nama_rekanan
      tgl_mulai
      tgl_selesai    
    }
  }
}
query dataKontrak ($id: ID!) {
  rekapKegiatan (id: $id) {
    id
    pekerjaan
    kegiatan
    desa
    kecamatan
    nomor_kontrak
    nilai_kontrak
    nama_rekanan
    tgl_mulai
    tgl_selesai
  }
}
    mutation updateKontrak(
  $id: ID!
  $program: String
  $kegiatan: String
  $pekerjaan: String
  $desa: String
  $kecamatan: String
  $nomor_kontrak: String
  $nilai_kontrak: String
  $nama_rekanan: String
  $tgl_mulai: Date
  $tgl_selesai: Date
){
  updateRekapKegiatan(
    input: {where: {id: $id} 
    data: {
    program: $program
    kegiatan: $kegiatan
    pekerjaan: $pekerjaan 
    desa: $desa 
    kecamatan: $kecamatan
    nomor_kontrak: $nomor_kontrak
    nilai_kontrak: $nilai_kontrak
    nama_rekanan: $nama_rekanan
    tgl_mulai: $tgl_mulai
    tgl_selesai: $tgl_selesai
    
    }}) {
    rekapKegiatan {
    id
    program
    kegiatan
    pekerjaan
    desa
    kecamatan
    nomor_kontrak
    nilai_kontrak
    nama_rekanan
    tgl_mulai
    tgl_selesai
    }
  }
}

