mutation createMap($lat: Float!, $long_: Float!, $pekerjaan: String!) {
  createMap(input: {data: {lat: $lat, long_: $long_, pekerjaan: $pekerjaan }}) {
    map {
      id
      lat
      long_
      pekerjaan
    }
  }
}
query mapsAll {
  maps {
    id
    lat
    long_
    pekerjaan
  }
  rekapKegiatans{
    id
    pekerjaan
    desa
    kecamatan
    nomor_kontrak
    nilai_kontrak
    nama_rekanan
    tgl_mulai
    tgl_selesai
  }
}