query SuratMasuk {
  suratMasuks{
    id
    asal_surat
    nomor_surat
    perihal_surat
    tgl_surat
    tgl_masuk
  }
}
mutation addSuratMasuk(
  $asal_surat: String,
  $nomor_surat: String,
  $perihal_surat: String,
  $tgl_surat: Date,
  $tgl_masuk: Date
){
  createSuratMasuk(input: {data:{
    asal_surat: $asal_surat
    nomor_surat: $nomor_surat
    perihal_surat:$perihal_surat
    tgl_surat: $tgl_surat
    tgl_masuk: $tgl_masuk
  }}){
    suratMasuk{
      id
      asal_surat
      nomor_surat
      perihal_surat
      tgl_surat
      tgl_masuk
    }
  }
}